[phases.setup]
nixPkgs = ["...", "dotnet-sdk"]

[phases.build]
cmds = [
    "cd 'bryx CRM' && dotnet restore 'bryx CRM.csproj'",
    "cd 'bryx CRM' && dotnet publish 'bryx CRM.csproj' -c Release -o /app/publish --no-self-contained"
]

[start]
cmd = "cd /app/publish && dotnet bryx_CRM.dll"
